services:
  payara-libria-service:
    image: payara/server-full:6.2025.8-jdk17
    environment:
      SECURE_ADMIN: "true"
      ADMIN_USER: "admin"
      ADMIN_PASSWORD: "admin"
    ports:
      - "8081:8080"
      - "4849:4848"
    volumes:
      - ./LibriaService/target/LibriaService.war:/opt/payara/appserver/glassfish/domains/domain1/autodeploy/LibriaService.war
      - ./LibriaService/files:/opt/payara/appserver/files

  payara-libria-webapp:
    image: payara/server-full:6.2025.8-jdk17
    environment:
      SECURE_ADMIN: "true"
      ADMIN_USER: "admin"
      ADMIN_PASSWORD: "admin"
      LIBRIA_SERVICE_URL: "http://payara-libria-service:8080/LibriaService/api"
    depends_on:
      - payara-libria-service
    ports:
      - "8082:8080"
      - "4850:4848"
    volumes:
      - ./LibriaWebApp/target/LibriaWebApp.war:/opt/payara/appserver/glassfish/domains/domain1/autodeploy/LibriaWebApp.war